charcount2.bin : charcount2.c
	gcc charcount2.c -o charcount2.bin
charcount.bin : charcount.c
	gcc charcount.c -o charcount.bin
exer_1_12.bin : exer_1_12.c
	gcc exer_1_12.c -o exer_1_12.bin
exer_1_13.bin : exer_1_13.c
	gcc exer_1_13.c -o exer_1_13.bin
exer_1_14.bin : exer_1_14.c
	gcc exer_1_14.c -o exer_1_14.bin
exer_1_16.bin : exer_1_16.c
	gcc exer_1_16.c -o exer_1_16.bin
exer_1_17.bin : exer_1_17.c
	gcc exer_1_17.c -o exer_1_17.bin
exer_1_18_new.bin : exer_1_18_new.c
	gcc exer_1_18_new.c -o exer_1_18_new.bin
exer_1_19.bin : exer_1_19.c
	gcc exer_1_19.c -o exer_1_19.bin
exer_1_3.bin : exer_1_3.c
	gcc exer_1_3.c -o exer_1_3.bin
exer_1_4.bin : exer_1_4.c
	gcc exer_1_4.c -o exer_1_4.bin
exer_1_5.bin : exer_1_5.c
	gcc exer_1_5.c -o exer_1_5.bin
exer_1_6.bin : exer_1_6.c
	gcc exer_1_6.c -o exer_1_6.bin
exer_1_7.bin : exer_1_7.c
	gcc exer_1_7.c -o exer_1_7.bin
exer1_8.bin : exer1_8.c
	gcc exer1_8.c -o exer1_8.bin
exer_1_9.bin : exer_1_9.c
	gcc exer_1_9.c -o exer_1_9.bin
inpt_to_output.bin : inpt_to_output.c
	gcc inpt_to_output.c -o inpt_to_output.bin
linecount.bin : linecount.c
	gcc linecount.c -o linecount.bin
powerfunc.bin : powerfunc.c
	gcc powerfunc.c -o powerfunc.bin
temp_conv2.bin : temp_conv2.c
	gcc temp_conv2.c -o temp_conv2.bin
temp_conv_for.bin : temp_conv_for.c
	gcc temp_conv_for.c -o temp_conv_for.bin
temp_conv_for_func.bin : temp_conv_for_func.c
	gcc temp_conv_for_func.c -o temp_conv_for_func.bin
track_maxline.bin : track_maxline.c
	gcc track_maxline.c -o track_maxline.bin
wordcount.bin : wordcount.c
	gcc wordcount.c -o wordcount.bin
all : charcount2.bin charcount.bin exer_1_12.bin exer_1_13.bin exer_1_14.bin exer_1_16.bin exer_1_17.bin exer_1_18_new.bin exer_1_19.bin exer_1_3.bin exer_1_4.bin exer_1_5.bin exer_1_6.bin exer_1_7.bin exer1_8.bin exer_1_9.bin inpt_to_output.bin linecount.bin powerfunc.bin temp_conv2.bin temp_conv_for.bin temp_conv_for_func.bin track_maxline.bin wordcount.bin
	echo "Build Done" 
clean:
	rm *.bin
