charcount.bin : charcount.c
	gcc charcount.c -o charcount.bin
exer_1_3.bin : exer_1_3.c
	gcc exer_1_3.c -o exer_1_3.bin
exer_1_4.bin : exer_1_4.c
	gcc exer_1_4.c -o exer_1_4.bin
exer_1_5.bin : exer_1_5.c
	gcc exer_1_5.c -o exer_1_5.bin
exer_1_6.bin : exer_1_6.c
	gcc exer_1_6.c -o exer_1_6.bin
exer_1_7.bin : exer_1_7.c
	gcc exer_1_7.c -o exer_1_7.bin
inpt_to_output.bin : inpt_to_output.c
	gcc inpt_to_output.c -o inpt_to_output.bin
temp_conv2.bin : temp_conv2.c
	gcc temp_conv2.c -o temp_conv2.bin
temp_conv_for.bin : temp_conv_for.c
	gcc temp_conv_for.c -o temp_conv_for.bin
all : charcount.bin exer_1_3.bin exer_1_4.bin exer_1_5.bin exer_1_6.bin exer_1_7.bin inpt_to_output.bin temp_conv2.bin temp_conv_for.bin
	echo "Build Done" 
clean:
	rm *.bin
