exer_1_3.bin : exer_1_3.c
	gcc exer_1_3.c -o exer_1_3.bin
exer_1_4.bin : exer_1_4.c
	gcc exer_1_4.c -o exer_1_4.bin
exer_1_5.bin : exer_1_5.c
	gcc exer_1_5.c -o exer_1_5.bin
temp_conv2.bin : temp_conv2.c
	gcc temp_conv2.c -o temp_conv2.bin
temp_conv_for.bin : temp_conv_for.c
	gcc temp_conv_for.c -o temp_conv_for.bin
all : exer_1_3.bin exer_1_4.bin exer_1_5.bin temp_conv2.bin temp_conv_for.bin
	echo "Build Done" 
clean:
	rm *.bin
